---
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: successfactors-middleware
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: successfactors-middleware-<namespace>
  rules:
    - accessStrategies:
        - handler: jwt
          config:
            jwks_urls:
            -  <your IAS oauth/certs>
      methods:
        - POST
      path: /webhook/success-factors
    - accessStrategies:
        - config: {}
          handler: noop
      methods:
        - POST
      path: /webhook/docusign
  service:
    name: successfactors-middleware
    port: 80